apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ledger-db-credentials
  labels:
    app.kubernetes.io/name: bank-of-anthos
    app.kubernetes.io/component: ledger-db
spec:
  refreshInterval: {{ .Values.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStoreName | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.ledgerDb.secretName | quote }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.ledgerDb.remoteKey | quote }}
