apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.storeName | quote }}
  labels:
    app.kubernetes.io/name: platform-external-secrets
    app.kubernetes.io/part-of: bank-of-anthos
spec:
  provider:
    aws:
      service: {{ .Values.aws.service | quote }}
      region: {{ .Values.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | quote }}
            namespace: {{ .Values.serviceAccount.namespace | quote }}
