apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-key
  labels:
    app.kubernetes.io/name: bank-of-anthos
    app.kubernetes.io/component: jwt
spec:
  refreshInterval: {{ .Values.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStoreName | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.jwt.secretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: jwtRS256.key
      remoteRef:
        key: {{ .Values.jwt.remoteKey | quote }}
        property: jwtRS256.key
    - secretKey: jwtRS256.key.pub
      remoteRef:
        key: {{ .Values.jwt.remoteKey | quote }}
        property: jwtRS256.key.pub
