apiVersion: v1
kind: Service
metadata:
  name: contacts
  labels:
    {{- include "bank-of-anthos.labels" . | nindent 4 }}
    app: contacts
    team: accounts
    tier: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.contacts.service.port }}
      targetPort: {{ .Values.contacts.service.port }}
  selector:
    app: contacts
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
  labels:
    {{- include "bank-of-anthos.labels" . | nindent 4 }}
    app: contacts
    team: accounts
    tier: backend
spec:
  replicas: {{ .Values.contacts.replicas }}
  selector:
    matchLabels:
      app: contacts
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "bank-of-anthos.labels" . | nindent 8 }}
        app: contacts
        team: accounts
        tier: backend
    spec:
      serviceAccountName: {{ include "bank-of-anthos.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 5
      containers:
        - name: contacts
          image: {{ include "bank-of-anthos.image" (dict "root" . "image" .Values.contacts.image) }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.contacts.service.port }}
          env:
            - name: VERSION
              value: {{ .Values.contacts.image.tag | quote }}
            - name: PORT
              value: {{ .Values.contacts.service.port | quote }}
            - name: ENABLE_TRACING
              value: {{ .Values.global.enableTracing | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.global.logLevel | quote }}
            - name: ACCOUNTS_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "bank-of-anthos.accountsDbSecretName" . }}
                  key: uri
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: accounts-db-config
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.contacts.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.contacts.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: publickey
              mountPath: /tmp/.ssh
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: publickey
          secret:
            secretName: {{ include "bank-of-anthos.jwtSecretName" . }}
            items:
              - key: jwtRS256.key.pub
                path: publickey
