apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bank-of-anthos.serviceAccountName" . }}
  labels:
    {{- include "bank-of-anthos.labels" . | nindent 4 }}
    team: platform
automountServiceAccountToken: true
