# remoteKey / host injected by Terraform via Argo.
clusterSecretStoreName: aws-secrets-manager
refreshInterval: 1h

jwt:
  secretName: jwt-key
  remoteKey: bank-of-anthos-jwt

accountsDb:
  secretName: accounts-db-credentials
  remoteKey: ""
  host: ""
  port: 5432
  dbName: accounts_db

ledgerDb:
  secretName: ledger-db-credentials
  remoteKey: ""
