apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-of-anthos-dev
  namespace: argocd
spec:
  project: bank-of-anthos
  source:
    repoURL: https://github.com/dbembnista1/aws-eks-bank-of-anthos.git
    path: charts/bank-of-anthos
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bank-of-anthos-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
